[package]
name = "geosign"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
qdrant-client = "1.11.0"
serde_json = "1.0.124"
tokio = { version = "1.39.2", features = ["rt-multi-thread", "rt", "macros"] }
tonic = "0.12.1"
lazy_static = "1.5.0"
